site_name: Fast X Fourier
site_url: https://fastxfourier.github.io/

nav:
  - Home: index.md
  - ทั่วไป:
    - อะไรคือ Competitive Programming?: general/intro-cp.md
    - สอวน. คอมพิวเตอร์: general/posn.md
    - แหล่งเรียนรู้: general/resources.md
  - การเขียนโปรแกรมเบื้องต้น:
    - บทนำ: prog-basic/index.md
    - วิธีการรันโปรแกรม: prog-basic/run-code.md
    - การเขียนโปรแกรมภาษา C:
      - Hello, World!: prog-basic/c/hello-world.md
      - ตัวแปร ชนิดข้อมูล และตัวดำเนินการ: prog-basic/c/variable.md
      - การส่งออกและนำเข้าข้อมูล: prog-basic/c/input-output.md
      - คำสั่ง if - else: prog-basic/c/if-else.md
  - โครงสร้างข้อมูลและอัลกอริทึ่ม:
    - อัลกอรึที่ม:
      - binary search: algorithm/binary-search.md
    # - การเขียนโปรแกรมภาษา C++:
    #   -
  - โจทย์: problems/index.md
