site_name: Fast X Fourier
site_url: https://fastxfourier.github.io/

nav:
  - Home: index.md
  - Data Structures and Algorithms:
    - Algorithms:
      - Bitmask DP: /algorithm/bitmask-dp
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  font:
    text: "Itim"
    size: "50px"
  palette:
    - scheme: default