site_name: Fast X Fourier
site_url: https://fastxfourier.github.io/

nav:
  - Home: index.md
  - Algorithms:
      - Algorithms: algorithms.md
      - Bitmask DP : algorithms/bitmask_dp.md
  - Problems:
      - Problems: problems/index.md
      - TOI:
          - 21:
              - toi21_duty_free : problems/toi21_duty_free.md
  - Others:
      - Others: others/index.md
  - About:
      - About: about/index.md

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - content.code.select
  font:
    text: "Itim"
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Dark mode
      primary: black
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/lightbulb-on-10
        name: Light mode
      primary: white
      accent: deep purple
      
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition

extra_css:
  - stylesheets/overrides.css
